---
abstract: 'TXOdds.com API Perl interface.'
author:
  - "\"Foxcool\" <\"\">"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Txodds
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Test::More: 0
  XML::LibXML::Simple: 0
version: 0.69
