--- #YAML:1.0
name:               WWW-Txodds
version:            0.68
abstract:           TXOdds.com API Perl interface.
author:
    - "Foxcool" <"">
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    HTTP::Request::Common:  0
    LWP::UserAgent:       0
    Test::More:           0
    XML::LibXML::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
